services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT:-3000}
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=userauth
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app:z
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db:z

volumes:
  mongo_data:
